---
title: "Statistics Report - Stories Summary"
params:
  fpath: "C:/Users/briney/Documents/JobDocs/LibStats/Reports/data"
  periodStart: "2018-01-01 00:00:00"
  periodEnd: "2018-05-30 23:59:59"
output: html_document
---

<!--
## Name: LibStats_report_RHD.Rmd
## Created: June 2018 by Kristin Briney
## Purpose: This Rmarkdown template will create a summary list of StatBot stories for
##          a specified date range.
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(tidyverse)
library(stringr)
library(lubridate)
library(knitr)

  ## Set parameters -- CHANGE AS NECESSARY
  pStart <-  ymd_hms(params$periodStart)
  pEnd <-  ymd_hms(params$periodEnd)
  pers <- params$person 

  
  
  ## Load consultation data
  
  finput <- paste(params$fpath, "Cons.csv", sep="/")
  Cons_all <- read_csv(finput)
  
  Cons <- filter(Cons_all, Cons_all$ConsDate>=pStart & Cons_all$ConsDate<=pEnd & !is.na(Cons_all$Story))

  ## Load presentation data
  
  finput <- paste(params$fpath, "Pres.csv", sep="/")
  Pres_all <- read_csv(finput)
  
  Pres <- filter(Pres_all, Pres_all$PresDateTime>=pStart & Pres_all$PresDateTime<=pEnd & !is.na(Pres_all$Story))
  
  ## Load transaction data
  
  finput <- paste(params$fpath, "Trans.csv", sep="/")
  Trans_all <- read_csv(finput)
  
  Trans <- filter(Trans_all, Trans_all$TransDateTime>=pStart & Trans_all$TransDateTime<=pEnd  & !is.na(Trans_all$Story))
```


### Time period: `r pStart` to `r pEnd`

## Consultations

### Consultation Stories

```{r Cstories}
  Cstories <- select(Cons, ConsDate, StaffDept, Story) %>% arrange(ConsDate)
  
  kable(Cstories, format="html")
```


## Presentations

### Presentation Stories

```{r Pstories}
  Pstories <- select(Pres, PresDateTime, StaffDept, Story) %>% arrange(PresDateTime)
  
  kable(Pstories, format="html")
```


## Transactions

### Transaction Stories

```{r Tstories}
  Tstories <- select(Trans, TransDateTime, StaffDept, Story) %>% arrange(TransDateTime)
  
  kable(Tstories, format="html")
```
